name: Generate APK

env:
  main_project_module: app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace
        # Catatan: Bagian echo secrets.STORE saya hapus untuk menghindari error 
        # jika kamu tidak memiliki file keystore di repositori ini.

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-Build-APK
          # Menggunakan wildcard (**/*.apk) agar otomatis menangkap 
          # app-release.apk ataupun app-release-unsigned.apk
          path: ${{ env.main_project_module }}/build/outputs/apk/**/*.apk
